### ISSUE TITLE
Adicionar renderização por MarkDown

### ISSUE THREAD

**Issue by lucasmedeiros** [OpenDevUFCG/poscomp#41]
**Descrição da melhoria:**
Adicionar um renderizador de MarkDown para as questões do POSCOMP.

**Necessidade da melhoria:**
Conforme sugerido por @JRobsonJr, seria melhor que fosse utilizado MarkDown para novos contribuidores escreverem as questões na mão do que simplesmente a utilização de um JSON. A ideia é tornar mais fácil de contribuir do que fosse em JSON ou LaTeX.

**Como ela pode ser implementada:**
Duas opções para implementar o renderizador:

1. Template gatsby
2. react-markdown

**Comment by jefersonf** [comment]
Olá,

Eu estava pensando numa possível solução para o problema de adição de LaTeX no enunciado dos problemas e usar MarkDown seria uma boa ideia. Porém, ainda sim seria necessário, por parte do contribuidor, inserir os símbolos LaTeX, seja manualmente ou utilizando uma referência (link) de uma imagem usando, por exemplo, o [codecogs](https://www.codecogs.com/latex/eqneditor.php). 

Tenho uma outra proposta de solução, relacionada a issue #62, em que se utiliza um _parser_ em conjunto com o Katex. Nesse caso, os símbolos LaTeX poderiam ser inseridos na _string_ do enunciado, desde que fossem colocados entre marcados de início e fim de um bloco LaTeX.

**Exemplo**

```
{
...
"enunciado": "Determine $ x $, tal que $ x^{2} + \\sqrt{x} = 6 $.",
...
}
```

Nesse caso, o marcador seria `$` e teríamos:

`[plain text] [latex] [plain text] [latex] [plain text]
`

O _parser_, nesse caso, aplicaria o Katex nos blocos `[latex]`, enquanto que nos demais blocos seriam elementos inline como `<span> ... </span>`.

Assim, o resultado do _parser_ seria algo como:

```
<div>
    <span>Determine </span>
    <KatexRender string="x" />
    <span>, tal que </span>
    <KatexRender string="x^{2} + \\sqrt{x} = 6" />
    <span>.</span>
</div>
```

O que acham?
