### ISSUE TITLE
Erro no Travis branch

### ISSUE THREAD

**Issue by ivynasantino** [OpenDevUFCG/poscomp#60]
**Descreva o bug**
Na branch master não está sendo aprovada pelo Travis.

**Reprodução do bug**
A branch master está com o seguinte erro: Some checks were not successful.

**Comportamento desejado**
Que todos os ramos sejam aprovados pelo Travis.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar na descrição do problema
![image](https://user-images.githubusercontent.com/18709508/66390396-fbcbfe00-e9a0-11e9-9bb8-7919a0300ffe.png)

**Comment by pedroespindula** [comment]
É o deploy que ta falhando. Vou dar uma olhada no pipeline e ver se resolvo.

**Comment by pedroespindula** [comment]
O que tava faltando era o token de acesso do github pro travis
