### ISSUE TITLE
Resolver configuração do Travis

### ISSUE THREAD

**Issue by ivynasantino** [OpenDevUFCG/poscomp#66]
**Descreva o bug**
A ferramenta de integração contínua está demorando muito para aprovar os PRs, ou não aprova.

**Reprodução do bug**
Passos para reproduzir o comportamento indesejado:
1. Só fazer um pr

**Comportamento desejado**
Não demorar para o Travis responder.

**Comment by marcelorl** [comment]
posso pegar esse

**Comment by lucasmedeiros** [comment]
@marcelorl Muito obrigado! :smile: 

Vou te dar o assign dessa.

**Comment by marcelorl** [comment]
@ivynasantino @lucasmedeiros 

eu fiz um teste no meu travis e o build demorou 1 min.

Quanto tempo seria demorado pra voces?

Pode colocar um print do build no travis?

A unica coisa que pode melhorar olhando por cima é pinar a versão do node de stable pra 12 que é a ultima de agora.

Tipo:

```
node_js:
  - "12.3.0"
```

assim o seu build consegue usar um cachezinho.

fora isso nada demais.

**Comment by marcelorl** [comment]
@ivynasantino @lucasmedeiros 

na verdade esqueci que dava pra ver o travis do repo. eu olhei e está bem aceitavel o tempo de build e deploy.

só teve um build que demorou 6 minutos, mas o resto está normal.

acho que essa issue pode ser fechada.

**Comment by lucasmedeiros** [comment]
Muito obrigado, @marcelorl!
